### ISSUE TITLE
Ghostscript 9.27: Unrecoverable error, exit code 1

### ISSUE THREAD

**Issue by 532910** [arsv/u2ps#2]
```
% cd /tmp
% git clone https://github.com/arsv/u2ps
% cd u2ps
% ./configure
% make
% path+=`pwd`
%  ./u2ps /tmp/test.c /tmp/test.ps
GPL Ghostscript 9.27: Unrecoverable error, exit code 1
gs failed, aborting
```

**Comment by arsv** [comment]
u2ps relies on absolute path for its postscript files, `/usr/share/u2ps` in default configuration.

If you want to run it from the source directory, try `./configure --devel` or `./configure --basedir=$PWD/res`.

**Comment by 532910** [comment]
Should it be better documented?
