### ISSUE TITLE
how do I manage word splitting at the end of the line?

### ISSUE THREAD

**Issue by trappedinspacetime** [arsv/u2ps#4]
First of all, thank you for developing this tool.
I have a text file which has long lines. I use `-w` switch to split long line into new line, however sometimes it splits a word incorrectly. 
How do I disable word splitting in `u2ps`?
Regards.

**Comment by arsv** [comment]
You have to use some external tool to wrap lines properly. I'm not sure there's readily available filter type tool, but vim can do it for sure and it should be trivial in perl. u2ps lacks the data needed to do that (bunch of unicode tables), and it's really not the right tool to add that functionality to.

That switch isn't really about wrapping lines as such. Try doing `cat file.txt` on a terminal; u2ps attemps to produce the same effect, except in a printable postscript form, and -w sets the width of the terminal.
