### ISSUE TITLE
bad file produced

### ISSUE THREAD

**Issue by 532910** [arsv/u2ps#5]
input file:
```c
// комментарий

int main()
{
	return 0;
}
```

u2ps works wo errors:
```
% ./u2ps /tmp/test.c /tmp/test.ps
```

printing `test.ps` on produces blank file. 

evince says `Loading...` permanently.

zathura says `Loading...` permanently and
```
undefined -21
error: Rendering failed (page 1)
```
in the loop on the console

http://sergio.outerface.net/misc/test.ps

debian sid, fonts-freefont-ttf is installed

**Comment by arsv** [comment]
test.ps lines 10 thru 16 — that text should not be there.

u2ps does not use -dSAFER anywhere but it looks like GS has it enabled by default since version 9.50 (Dec 2019). https://www.ghostscript.com/doc/9.50/Use.htm#Safer

**Comment by arsv** [comment]
https://github.com/arsv/u2ps/commit/804018c35ce6136c4277ef72a26463a4f8bfb4a7
